version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: datawarehouse_test

    environment:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/datawarehouse_test"

    steps:
      - checkout

      - restore_cache
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # if cache for exact version of `requirements.txt` is not present then load any most recent one
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      
      - save_cache
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          path: 
            - ./venv

      - run:
          name: Set up database
          command: |
            . venv/bin/activate
            flask create-db

      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Start flask server
          command: |
            . venv/bin/activate
            python3 app.py
          background: true

      - run:
          name: Wait for flask server to start
          command: sleep 2

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 tests.py

workflows:
  goTravel-build-and-test:
    jobs:
      - build-and-test
